[package]
name        = "voxidian-editor"
version     = "0.1.0"
authors     = ["LighthouseMC <https://github.com/LighthouseMC>"]
description = "Simple web-based code editor (server)."
license     = "LGPL-3.0"

homepage   = "https://github.com/LighthouseMC"
repository = "https://github.com/LighthouseMC/VoxidianEditor"

edition = "2024"

[lints.rust]
unused_parens = "allow"


[dependencies.rouille]
version = "3.6"

[dependencies.async-std]
version = "1.13"

[dependencies.const_format]
version = "0.2"


[dev-dependencies.async-std]
version = "*"
features = [ "attributes" ]
