[package]
name        = "voxidian-editor"
version     = "0.1.0"
authors     = ["LighthouseMC <https://github.com/LighthouseMC>"]
description = "Simple web-based code editor (server)."
license     = "LGPL-3.0"

homepage   = "https://github.com/LighthouseMC"
repository = "https://github.com/LighthouseMC/VoxidianEditor"

edition = "2024"

[lints.rust]
unused_parens = "allow"


[dependencies.voxidian-logger]
path = "../voxidian-logger"
[dependencies.voxidian-database]
path = "../voxidian-database"

[dependencies.tide]
version = "0.16"
[dependencies.tide-websockets]
version = "0.4"

[dependencies.async-std]
version = "1.13"
[dependencies.futures]
version = "0.3"

[dependencies.const_format]
version = "0.2"

[dependencies.openssl]
version = "0.10"


[dev-dependencies.async-std]
version = "*"
features = [ "attributes" ]

[dev-dependencies.chrono]
version = "0.4"

[dev-dependencies.openssl]
version = "0.10"
